apiVersion: v1
data:
  driver-image: quay.io/yhwang/lm-eval-aas-driver:latest
  pod-image: quay.io/yhwang/lm-eval-aas-flask:test
  driver-serviceaccount: driver
  pod-checking-interval: "10s"
  image-pull-policy: Always
  grpc-service: THIS_WILL_BE_REPLACED
  grpc-port: "8082"
kind: ConfigMap
metadata:
  name: configmap
