---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-foundation-model-stack-github-com-github-com-v1beta1-lmevaljob
  failurePolicy: Fail
  name: mlmevaljob.kb.io
  rules:
  - apiGroups:
    - foundation-model-stack.github.com.github.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - lmevaljobs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-foundation-model-stack-github-com-github-com-v1beta1-lmevaljob
  failurePolicy: Fail
  name: vlmevaljob.kb.io
  rules:
  - apiGroups:
    - foundation-model-stack.github.com.github.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - lmevaljobs
  sideEffects: None
