---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-lm-eval-service-github-com-v1beta1-evaljob
  failurePolicy: Fail
  name: mevaljob.kb.io
  rules:
  - apiGroups:
    - lm-eval-service.github.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - evaljobs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-lm-eval-service-github-com-v1beta1-evaljob
  failurePolicy: Fail
  name: vevaljob.kb.io
  rules:
  - apiGroups:
    - lm-eval-service.github.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - evaljobs
  sideEffects: None
