apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - genai-key.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
images:
  - name: quay.io/lm-eval-aas
    newTag: latest
