apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: driver-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - foundation-model-stack.github.com.github.com
  resources:
  - lmevaljobs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - foundation-model-stack.github.com.github.com
  resources:
  - lmevaljobs/status
  verbs:
  - get
  - patch
  - update
