apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: fms-lm-eval-service
    app.kubernetes.io/managed-by: kustomize
  name: driver-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: driver-role
subjects:
- kind: ServiceAccount
  name: driver
