apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: driver-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lm-eval-service.github.com
  resources:
  - evaljobs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lm-eval-service.github.com
  resources:
  - evaljobs/status
  verbs:
  - get
  - patch
  - update
