# permissions for end users to view evaljobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fms-lm-eval-service
    app.kubernetes.io/managed-by: kustomize
  name: evaljob-viewer-role
rules:
- apiGroups:
  - lm-eval-service.github.com
  resources:
  - evaljobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lm-eval-service.github.com
  resources:
  - evaljobs/status
  verbs:
  - get
